export const reducerCases = {
    SET_TOKEN:"SET_TOKEN",
    SET_USER: "SET_USER",
    SET_ARTIST: "SET_ARTIST",
    SET_TRACKS: "SET_TRACKS",
    SET_TOPARTISTS: "SET_TOPARTISTS",
    SET_TOPTRACKS: "SET_TOPTRACKS", // use this
}